language: cpp
os: linux
dist: bionic

env:
  global:
    - travis_boost_version=1.71.0
  matrix:
    - configuration=Debug   platform=x64
    - configuration=Release platform=x64

before_script:
  - ./cmake/build/boost/build_travis.sh --with-filesystem --with-program_options --with-test

script:
  - |-
    ./cmake/build/build_travis.py        \
        --configuration "$configuration" \
        --install "$HOME/install"        \
        --boost "$HOME/boost_1_71_0"     \
        --boost-librarydir "$HOME/boost_1_71_0/stage/$platform/${configuration,,}/lib" \
        -- -DENABLE_TESTS=ON
  - "$HOME/install/bin/unit_tests"
