language: cpp
os: linux
dist: focal

addons:
  apt:
    packages:
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-regex-dev
      - libboost-test-dev

env:
  jobs:
    - configuration=Debug   platform=x64
    - configuration=Release platform=x64

script:
  - cd cmake
  - >-
    python3 -m project.ci.travis.cmake
    --install "$HOME/install"
    --
    -D ENABLE_TESTS=ON

  - "$HOME/install/bin/math-server-unit-tests"
  - "$HOME/install/bin/math-server-benchmarks"
  - ../test/stress_test.sh

jobs:
  fast_finish: true

  _clear: &clear
    language: shell
    addons: {apt: {packages: []}}
    script: []

  _docker: &docker
    <<: *clear
    services: [docker]

  include:
    - <<: *clear
      name: Run clang-format
      if: branch = master
      addons:
        apt:
          packages:
            - clang-format-9
      script: ./cmake/tools/clang-format.py --clang-format clang-format-9

    - <<: *docker
      name: 'Docker: build native images'
      script: make docker/build

    - <<: *docker
      name: 'Docker: build native images using Compose'
      script: make compose/build

    - <<: *docker
      stage: publish
      name: 'Docker: build & publish multi-arch images'
      if: branch = master
      # buildx isn't installed on Focal.
      before_install: make buildx/install
      script: make login && make buildx/create && make buildx/push
