language: cpp
os: linux
dist: bionic

addons:
  apt:
    update: true
    packages:
      - cmake
      - g++-multilib
    sources:
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
        key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'

env:
  global:
    - travis_boost_version=1.71.0
  matrix:
    - configuration=Debug   platform=x86
    - configuration=Release platform=x86
    - configuration=Debug   platform=x64
    - configuration=Release platform=x64

before_script:
  - ./cmake/ci/boost/build_travis.py -- link=static --with-filesystem --with-program_options --with-test

script:
  - |-
    ./cmake/ci/build_travis.py \
        --install "$HOME/install" \
        -- \
        -D "CMAKE_TOOLCHAIN_FILE=cmake/toolchains/gcc-$platform.cmake" \
        -D "BOOST_ROOT=$HOME/boost_1_71_0" \
        -D "BOOST_LIBRARYDIR=$HOME/boost_1_71_0/stage/$platform/$configuration/lib" \
        -D ENABLE_TESTS=ON
  - "$HOME/install/bin/math-server-unit-tests"
  - "$HOME/install/bin/math-server-benchmarks"
